### ISSUE TITLE
gcc 4.8.3 not supported

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/wreport#3]
When compiling with gcc 4.8.3:

```
make[2]: Entering directory `/autofs/nethomes/edigiacomo/src/wreport/wreport'
...
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -DTABLE_DIR=\"/usr/local/share/wreport\" -I.. -g -O2 -std=gnu++11 -Wall -MT utils/tests.lo -MD -MP -MF utils/.deps/tests.Tpo -c utils/tests.cc  -fPIC -DPIC -o utils/.libs/tests.o
In file included from utils/tests.cc:9:0:
utils/tests.h: In member function 'void wreport::tests::TestCase::add_method(const string&, FUNC, Args&& ...)':
utils/tests.h:701:56: error: expected ',' before '...' token
         methods.emplace_back(name, [test_function, args...]() { test_function(args...); });
                                                        ^
utils/tests.h:701:56: error: expected identifier before '...' token
utils/tests.h:701:59: error: parameter packs not expanded with '...':
         methods.emplace_back(name, [test_function, args...]() { test_function(args...); });
                                                           ^
utils/tests.h:701:59: note:         'args'
utils/tests.h: In lambda function:
utils/tests.h:701:83: error: expansion pattern 'args' contains no argument packs
         methods.emplace_back(name, [test_function, args...]() { test_function(args...); });
...
```
Maybe is related to [gcc bug #41933](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=41933)?

**Comment by edigiacomo** [comment]
wreport now compiles with gcc 4.8.3. Close #3.
